[versions]
# year = major, month = minor
# major * 1000000, minor * 1000, patch * 1
smarthome-app-code = "26001001"
smarthome-app-name = "2026.01-SNAPSHOT"

smarthome-domain = "2026.01-SNAPSHOT"
smarthome-api = "2026.01-SNAPSHOT"

android-gradle-plugin = "9.1.0"
android-sdk-compile = "36"
android-sdk-min = "31"
android-sdk-target = "36"

androidx-activity = "1.12.4"
androidx-appcompat = "1.7.1"
androidx-navigation = "1.1.0-alpha03"

compose-unstyled = "1.49.6"

detekt = "2.0.0-alpha.2"
detekt-compose-rules = "0.5.6"

jetbrains-compose = "1.10.2"

jvm-toolchain = "21"

kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"

ktlint = "1.8.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-navigation-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-navigation" }

compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "jetbrains-compose" }
compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "jetbrains-compose" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "jetbrains-compose" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "jetbrains-compose" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "jetbrains-compose" }
compose-unstyled = { group = "com.composables", name = "composeunstyled", version.ref = "compose-unstyled" }
compose-unstyled-theming = { group = "com.composables", name = "composeunstyled-theming", version.ref = "compose-unstyled" }
compose-unstyled-primitives = { group = "com.composables", name = "composeunstyled-primitives", version.ref = "compose-unstyled" }

detekt = { group = "dev.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose-rules" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }

detekt = { id = "dev.detekt", version.ref = "detekt" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

marsys-smarthome-detekt = { id = "network.marsys.conventions.detekt" }
marsys-smarthome-apply-ios-version = { id = "network.marsys.conventions.apply-ios-version" }
